export const expensesTypesEmail = [
  "Current Month",
  "Last Month",
  "All Expenses",
  "Within Range Expenses",
  "Expenses By Name",
  "Expenses By Type",
  "Expenses By Payment Method",
  "Expenses By Type and Payment Method",
  "Expenses Within Amount Range",
  "Particular Month Expenses",
  "Today",
  "Yesterday",
  "Particular Date Expenses",
  "Current Week",
  "Last Week",
];

export const AuditLogsDataEmail = [
  "Current Month Logs",
  "Last Month Logs",
  "Current Year Logs",
  "Last Year Logs",
  "Current Week Logs",
  "Last Week Logs",
  "Today Logs",
  "Logs for Specific Year",
  "Logs for Specific Month",
  "Logs for Specific Day",
  "Logs by Action Type",
  "Logs by Expense ID and Action Type",
  "Logs from Last N Minutes",
  "Logs from Last N Hours",
  "Logs from Last N Days",
  "Logs from Last N Seconds",
  "Logs from Last 5 Minutes",
  "All Audit Logs",
  "Logs by Expense ID",
];

export const expenseSummaryEmail = [
  "Monthly Wise Daily Expense Summary",
  "Yearly Wise Daily Expense Summary",
  "Expense Summary for Specific Date",
  "Payment Method Summary",
  "Monthly Summary",
  "Yearly Summary",
  "Summary Between Dates",
];
